using System.ComponentModel.DataAnnotations;

namespace EmployeManagementApi1.Models
{
    public class Employee
    {
        public int Id { get; set; }  // Auto-generated by SQL

        [Required]
        [MinLength(2)]
        public string Name { get; set; }

        [Required]
        public string Department { get; set; }

        [Range(18, 60)]
        public int Age { get; set; }
    }
}
